{"uuid": "aeb7da29-a324-4fca-b274-1b05294fa6c6", "children": ["adc66f86-6eb8-4595-81df-d7c8c905dc46", "4bf877d0-545e-4fb5-90c0-9a8e7bdd3e93", "acf86969-a19d-49d2-a51e-54922352aa74"], "befores": [{"name": "beforeClass", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20241ms.\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20241ms.\n    at getResponseForW3CError (/Users/jarvis/.npm-global/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)\n    at asyncHandler (/Users/jarvis/.npm-global/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)\n", "trace": "  File \"/Users/jarvis/Documents/training/online/appium/appiumPythonFramework/venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/jarvis/Documents/training/online/appium/appiumPythonFramework/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/jarvis/Documents/training/online/appium/appiumPythonFramework/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/jarvis/Documents/training/online/appium/appiumPythonFramework/tests/conftest.py\", line 10, in beforeClass\n    driver = objectDriver.getDriver()\n  File \"/Users/jarvis/Documents/training/online/appium/appiumPythonFramework/base/Driver.py\", line 15, in getDriver\n    driver = webdriver.Remote('http://127.0.0.1:4723/wd/hub', caps)\n  File \"/Users/jarvis/Documents/training/online/appium/appiumPythonFramework/venv/lib/python3.10/site-packages/appium/webdriver/webdriver.py\", line 230, in __init__\n    super().__init__(\n  File \"/Users/jarvis/Documents/training/online/appium/appiumPythonFramework/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/Users/jarvis/Documents/training/online/appium/appiumPythonFramework/venv/lib/python3.10/site-packages/appium/webdriver/webdriver.py\", line 320, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n  File \"/Users/jarvis/Documents/training/online/appium/appiumPythonFramework/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/jarvis/Documents/training/online/appium/appiumPythonFramework/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1658613208885, "stop": 1658613233256}], "start": 1658613208885, "stop": 1658613233435}